form:
    path: /
    controller: App\Controller\SurveyController::renderSurveyForm
search_survey:
    path: /search-survey
    controller: App\Controller\SurveyController::renderSurveySearch
save_survey:
    path: /save-survey
    controller: App\Controller\SurveyController::saveSurvey
print_survey:
    path: /print-survey
    controller: App\Controller\SurveyController::printSurvey